liip_imagine:
    driver: "gd"

    twig:
        mode: lazy

    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.products_fs_filesystem

    data_loader: flysystem_loader

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.products_fs_filesystem
                root_url: '%app.uploads_base_url%'
                cache_prefix: media/cache
                visibility: public

    cache: flysystem_resolver

    filter_sets:
        small_thumbnail:
            filters:
                thumbnail:
                    size: [ 90, 90 ]
                    mode: outbound
                    allow_upscale: true
        medium_thumbnail:
            filters:
                thumbnail:
                    size: [ 150, 150 ]
                    mode: outbound
                    allow_upscale: true

        large_thumbnail:
            filters:
                thumbnail:
                    size: [ 200, 200 ]
                    mode: outbound
                    allow_upscale: true
        medium_image:
            filters:
                thumbnail:
                    size: [ 342, 342 ]
                    mode: outbound
                    allow_upscale: true
