framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'no-reply@%env(DEFAULT_DOMAIN)%.com'
        headers:
            From: '%env(DEFAULT_DOMAIN)% <no-reply@%env(DEFAULT_DOMAIN)%.com>'

when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['%env(DEV_MAIL_RECIPIENT)%']

