twig:
    file_name_pattern: '*.twig'
    form_themes: [
        '@TalesFromADevFlowbite/form/default.html.twig',
        'bundles/TalesFromADevFlowbiteBundle/form/custom_form_theme.html.twig'
    ]
    paths:
        'assets/styles': styles
    globals:
        domain: '%env(SITE_DOMAIN)%'
        product_uploads: '%app.product_uploads%'
    debug: true

when@test:
    twig:
        strict_variables: true
