twig:
    file_name_pattern: '*.twig'
    form_themes: [
        '@TalesFromADevFlowbite/form/default.html.twig',
        'bundles/TalesFromADevFlowbiteBundle/form/custom_form_theme.html.twig',
        'form/turnstile.html.twig'
    ]
    paths:
        'assets/styles': styles
    globals:
        domain: '%env(DEFAULT_DOMAIN)%'
        product_uploads: '%app.product_uploads%'
        playground_mode: '%env(bool:PLAYGROUND_MODE)%'
        turnstile_site_key: '%env(TURNSTILE_SITE_KEY)%'
    debug: true

when@test:
    twig:
        strict_variables: true
