# ===============================
# Docker Compose: Local development configuration (symfony server)
# ===============================
# Defines basic services for local development tools.
# Use with local symfony server or other dev setups.

services:
  # --- MySQL Database (Dev local) ---
  database:
    image: mysql:8.4
    ports:
      - "127.0.0.1:3306:3306"   # Expose for dev tools (localhost only).
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
      # Default username/pw set in .env
    volumes:
      - db-data:/var/lib/mysql    # Persist DB data between restarts
    healthcheck:
      # Wait for MySQL to be ready
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped


  # --- Redis Cache (Dev local) ---
  redis:
    image: redis:8.4-alpine
    ports:
      - "127.0.0.1:6379:6379"   # Localhost only
    environment:
      REDIS_PASSWORD: password    # Dev pw (never use in prod!)
    volumes:
      - redis_data:/data    # Persist redis data between restarts
    healthcheck:
      # Wait for Redis to be ready
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  # --- RabbitMQ Message Broker (Dev local) ---
  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    ports:
      - "127.0.0.1:5672:5672"      # AMQP protocol (localhost only)
      - "127.0.0.1:15672:15672"    # RabbitMQ Management UI (localhost only)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped


  # --- PhpMyAdmin (Dev local Tool) ---
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "127.0.0.1:8080:80"   # Access at http://localhost:8080
    environment:
      PMA_HOST: database
    restart: unless-stopped


  # --- PhpMyAdmin (Prod Tool - requires ssh tunnel) ---
  phpmyadmin-prod:
    image: phpmyadmin
    ports:
      - "127.0.0.1:8081:80"   # Access at http://localhost:8081
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3307
    volumes:
      - ./docker/phpmyadmin/prod-custom-footer.php:/var/www/html/config.footer.inc.php
    restart: unless-stopped


  # --- Mailpit (Dev local SMTP capture) ---
  mailer:
    image: axllent/mailpit
    ports:
      - "127.0.0.1:1025:1025"   # SMTP for app to deliver to Mailpit (localhost only)
      - "127.0.0.1:8025:8025"   # Web UI for inspecting mails (localhost only)
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


# --- Volumes (Dev local)  ---
volumes:
  db-data:      # MySQL data
  redis_data:   # Redis data
