services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php-dev
    command: sh -c "wait-for-it database:3306 --timeout=60 --strict -- php-fpm"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "php", "bin/console", "about" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: nginx-dev
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      php:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-kf", "https://localhost" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s

  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s
  ###< doctrine/doctrine-bundle ###

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  messenger:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: messenger-dev
    command: sh -c "wait-for-it database:3306 --timeout=60 --strict -- php bin/console messenger:consume async --time-limit=3600 --sleep=5"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "bin/console", "about"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  cron:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: cron-dev
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "php", "bin/console", "about" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
