services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php-prod
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      MAILER_DSN: ${MAILER_DSN}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_ACCESS_ID: ${AWS_S3_ACCESS_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}

  nginx:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: nginx-prod
    volumes:
      - /etc/letsencrypt/live/supplymars.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/supplymars.com/privkey.pem:/etc/ssl/private/privkey.pem:ro

  database:
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  messenger:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php-prod
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      MAILER_DSN: ${MAILER_DSN}
